# -*- coding: utf-8 -*-
"""Intent Parsing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ZpORg1LIEaTacO1L52GXxYeNGnGEIYz
"""

import json
from typing import Dict

class IntentParser:
    """
    The Bridge between Natural Language and Game Code.
    Uses the LLM to classify user input into strict JSON commands.
    """

    def __init__(self, llm_client):
        self.llm = llm_client

    def parse_input(self, user_text: str, valid_targets: list) -> Dict:
        """
        Input: "I wanna smash that goblin with my hammer."
        Output: {"action": "attack", "target": "goblin_sniper_01"}
        """

        system_prompt = f"""
        You are a Game Logic Parser. Your job is to translate user speech into a JSON command.

        AVAILABLE ACTIONS:
        - "attack": Combat actions. Requires 'target' from the list: {valid_targets}.
        - "move": Travel actions. Requires 'direction' (north, south, east, west).
        - "investigate": Searching or looking closely.
        - "speak": Talking to NPCs.
        - "meta": Questions about rules or out-of-character talk.

        Output ONLY JSON. Example: {{"action": "attack", "target": "goblin_01"}}
        """

        # Call the LLM (Simulated here)
        response_text = self.llm.generate_json(user_text, system_prompt)

        try:
            return json.loads(response_text)
        except json.JSONDecodeError:
            # Fallback if AI fails
            return {"action": "meta", "content": "Parsing Error"}

# Example Usage
# parser = IntentParser(my_llm_client)
# cmd = parser.parse_input("Hit the skeleton", valid_targets=["skeleton_warrior"])
# print(cmd) # {'action': 'attack', 'target': 'skeleton_warrior'}