# -*- coding: utf-8 -*-
"""Lore Database & Filtering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LkjJ7vstzuhEfqDtGBVx10WqSeC6mWvr
"""

from typing import List, Dict, Optional
from pydantic import BaseModel, Field

# --- 1. THE KNOWLEDGE ATOMS ---

class LoreFragment(BaseModel):
    """A single piece of information about the world."""
    id: str
    category: str # e.g., "history", "faction", "gods", "geography"
    content: str  # "The Sun King was betrayed by his brother."
    tags: List[str] # ["sun_kingdom", "betrayal", "royal_family"]

    # Secret Management
    is_secret: bool = False
    discovery_dc: int = 15 # Difficulty Check to learn this (History/Arcana)
    known_by_player: bool = False

class AtmosphereProfile(BaseModel):
    """The 'Vibe' of a location."""
    visuals: List[str] # ["crumbling stone", "bioluminescent moss"]
    sounds: List[str] # ["distant dripping", "scuttling claws"]
    smells: List[str] # ["ozone", "rot"]
    lighting: str # "Dim purple glow"

# --- 2. THE CONTEXT CONTAINERS ---

class WorldBible(BaseModel):
    """The Master Encyclopedia (Macro Layer)."""
    world_name: str
    global_lore: List[LoreFragment]
    factions: Dict[str, str] # {"Cult of Worms": "Wants to eat the sun"}

    # This vector index is conceptual; in prod use ChromaDB/Pinecone
    def query_lore(self, query_tags: List[str]) -> List[LoreFragment]:
        """The 'Librarian': Finds lore relevant to specific tags."""
        relevant_chunks = []
        for fragment in self.global_lore:
            # Simple intersection logic (in prod, use semantic search)
            if any(tag in query_tags for tag in fragment.tags):
                relevant_chunks.append(fragment)
        return relevant_chunks

class SessionContext(BaseModel):
    """The 'Cheat Sheet' attached to the Session JSON (Meso Layer).
    This is small enough to fit in the LLM Context Window.
    """
    location_name: str
    atmosphere: AtmosphereProfile

    # We only copy the RELEVANT lore here, not the whole Bible
    local_history: List[LoreFragment]
    local_factions: List[str]

# --- 3. THE INJECTION LOGIC (MESO-GENERATOR) ---

def hydrate_session_with_lore(world_db: WorldBible,
                              location_tags: List[str],
                              biome_type: str) -> SessionContext:
    """
    Runs before the session starts.
    Builds the 'Setting Guide' for this specific adventure.
    """

    # 1. Ask the Librarian for relevant history
    # e.g., location_tags = ["elven_ruins", "forest"]
    relevant_history = world_db.query_lore(location_tags)

    # 2. Generate Atmosphere (can be random or template-based)
    atmosphere = AtmosphereProfile(
        visuals=["vines choking statues", "sunlight filtering through canopy"],
        sounds=["birds chirping nervously", "cracking branches"],
        smells=["pine needles", "old stone"],
        lighting="Dappled sunlight"
    )
    if biome_type == "crypt":
        atmosphere.lighting = "Pitch black"
        atmosphere.smells = ["dust", "stagnant air"]

    # 3. Assemble the Context Package
    context = SessionContext(
        location_name="The Whispering Ruins",
        atmosphere=atmosphere,
        local_history=relevant_history,
        local_factions=["Forest Guardians"]
    )

    return context

# --- EXAMPLE USAGE ---

if __name__ == "__main__":
    # 1. Define the World (Macro)
    my_world = WorldBible(
        world_name="Eldoria",
        global_lore=[
            LoreFragment(id="h1", category="history", content="The Elves vanished in the Red Year.", tags=["elf", "history"]),
            LoreFragment(id="h2", category="history", content="The Dwarves built steam engines.", tags=["dwarf", "tech"]),
            LoreFragment(id="h3", category="magic", content="Magic is powered by blood.", tags=["magic", "universal"])
        ],
        factions={"Iron Legion": "Military oppressors"}
    )

    # 2. Player enters an Elven Ruin (Meso)
    # The system filters the massive DB down to just what matters NOW.
    current_session_context = hydrate_session_with_lore(
        my_world,
        location_tags=["elf"],
        biome_type="forest"
    )

    print(f"--- Context Loaded for {current_session_context.location_name} ---")
    print(f"Atmosphere: {current_session_context.atmosphere.lighting}")
    print("Relevant Lore Definitions:")
    for lore in current_session_context.local_history:
        print(f"- {lore.content}")

    # Note: 'Dwarves' lore was NOT loaded, saving token space.