# -*- coding: utf-8 -*-
"""Main Game Loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X9K0C_xGF_XQMwpUfWUBOyMPkc45SwNt
"""

import time
# Import the components we designed previously
# from dungeon_master_schemas import RoomNode
# from table_logic_engine import TableLogicEngine
# from memory_architecture import ContextManager, MemoryBlock
# from lore_system_architecture import hydrate_session_with_lore
from llm_interface import LLMGateway
from intent_parser import IntentParser

def main():
    print("--- INITIALIZING AI DUNGEON MASTER ---")

    # 1. SETUP PHASE (Macro & Meso Layers)
    llm = LLMGateway(api_key="sk-...")
    parser = IntentParser(llm)

    # Simulate loading the "Session" we generated earlier
    current_room = {
        "id": "room_01",
        "title": "Damp Crypt",
        "exits": ["north"],
        "entities": ["goblin_01"],
        "description_initial": "A cold, damp crypt."
    }

    # 2. START GAME LOOP (Micro Layer)
    game_running = True
    while game_running:

        # A. INPUT (STT)
        # In a real app, this waits for microphone input
        user_audio = input("\n🎤 You (Type to simulate voice): ")
        if user_audio == "quit":
            break

        # B. INTENT PARSING (Logic Router)
        # The Parser looks at valid targets in the room to help the AI decide
        user_intent = parser.parse_input(user_audio, valid_targets=current_room['entities'])
        print(f"⚙️ [SYSTEM PARSED]: {user_intent}")

        # C. LOGIC EXECUTION (State Update)
        # We pass the intent to the TableLogicEngine (from previous steps)
        # result = logic_engine.process_action(user_intent, current_room)

        # Simulating Logic Result:
        if user_intent.get('action') == 'attack':
            logic_result = "Success. Goblin takes 5 damage. Goblin dies."
            current_room['entities'] = [] # Update State
        else:
            logic_result = "You look around. Nothing happens."

        # D. NARRATIVE GENERATION (The Storyteller)
        # Combine the Logic Result with the Lore/Atmosphere
        narrative_prompt = f"""
        Action Result: {logic_result}
        Current Room: {current_room['title']}
        Lore Context: Goblins here fear fire.

        Write a 2-sentence description of this outcome.
        """

        story_output = llm.generate_narrative("You are a DM.", narrative_prompt)

        # E. OUTPUT (TTS)
        llm.text_to_speech(story_output)

if __name__ == "__main__":
    main()