# -*- coding: utf-8 -*-
"""Speaker Identification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o3FOLIQZwOMAbLiKgDZfujEU1wvoggkp
"""

class LocalSpeakerManager:
    """
    Handles local voice attribution.
    """
    def __init__(self, party_state):
        self.party = party_state
        self.active_speaker_id = list(party_state.members.keys())[0]

    def set_speaker_manual(self, player_id: str):
        """Triggered by clicking a button on the UI."""
        self.active_speaker_id = player_id

    def process_voice_input(self, audio_data):
        """
        Advanced: Use a diarization model (like Pyannote) to detect
        who is speaking based on voice frequency.
        """
        # 1. Identify voice fingerprint
        # 2. Map fingerprint to user_id
        # 3. return self.active_speaker_id
        pass

    def construct_intent_context(self, text: str):
        """
        Wraps the raw STT text with the identity of the speaker
        so the Intent Parser knows who is acting.
        """
        speaker = self.party.members[self.active_speaker_id]
        return f"Speaker: {speaker.name} ({speaker.player_name}). Action: {text}"