# -*- coding: utf-8 -*-
"""Structure Definitions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QVTkkqVHJ-Vs6B1XeTI92zVgqa0g7ZDK
"""

from typing import List, Dict, Optional, Union
from pydantic import BaseModel, Field
from enum import Enum

# --- ENUMS (Fixed Rule Sets) ---
class Difficulty(str, Enum):
    EASY = "easy"
    MEDIUM = "medium"
    HARD = "hard"
    DEADLY = "deadly"

class RoomType(str, Enum):
    CORRIDOR = "corridor"
    CHAMBER = "chamber"
    PUZZLE = "puzzle"
    BOSS_ARENA = "boss_arena"
    SAFE_HAVEN = "safe_haven"

# --- MICRO LAYER (The Room/Encounter) ---

class EntityStats(BaseModel):
    """The 'Character Sheet' for a monster or NPC."""
    name: str
    hp_current: int
    hp_max: int
    ac: int
    attacks: List[Dict[str, str]] = Field(..., description="List of attacks, e.g., [{'name': 'Claw', 'dmg': '1d6+2'}]")
    is_hostile: bool = True

class LootItem(BaseModel):
    name: str
    value_gp: int
    description: str
    is_magical: bool

class RoomNode(BaseModel):
    """A single node in the dungeon graph."""
    id: str
    title: str
    type: RoomType
    description_initial: str = Field(..., description="Read when entering for the first time.")
    description_cleared: str = Field(..., description="Read when returning after clearing.")

    # State flags
    is_visited: bool = False
    is_locked: bool = False
    key_required_id: Optional[str] = None

    # Contents (Mutable)
    entities: List[EntityStats] = []
    loot: List[LootItem] = []

    # Navigation
    exits: Dict[str, str] = Field(..., description="Direction -> Target Room ID mapping. e.g. {'north': 'room_02'}")

# --- MESO LAYER (The Session/Module) ---

class SessionModule(BaseModel):
    """The 'Adventure Module' generated for a single session."""
    session_id: str
    location_name: str
    dungeon_level: int

    # The Map (Adjacency List + Data)
    rooms: Dict[str, RoomNode]

    # Global Session State
    turn_counter: int = 0
    alert_level: int = 0  # 0 = Quiet, 5 = Alarm raised

# --- MACRO LAYER (The Campaign/World) ---

class PlotPoint(BaseModel):
    """A node in the high-level story graph."""
    id: str
    summary: str
    is_completed: bool = False
    required_flags: List[str] = [] # e.g., ["found_ancient_key"]
    next_points: List[str] = [] # IDs of possible next plot points

class NPCProfile(BaseModel):
    """High-level NPC data (not stats, but role/relationships)."""
    id: str
    name: str
    role: str
    relationship_to_party: int = 0 # -100 (Nemesis) to 100 (Ally)
    current_location_id: Optional[str] = None

class CampaignState(BaseModel):
    """The Master Save File."""
    campaign_id: str
    world_name: str
    genre: str

    # The Story Graph
    story_graph: Dict[str, PlotPoint]
    current_plot_node: str

    # The Cast
    npcs: Dict[str, NPCProfile]

    # Inventory of generated sessions
    archived_sessions: List[str] # IDs of past sessions
    active_session: Optional[SessionModule] # The currently loaded dungeon

# Example Usage Comment:
# generated_dungeon = SessionModule(...)
# print(generated_dungeon.json(indent=2))